# see https://github.com/ankane/blazer for more info

data_sources:
#  main:
#    url: <%= ENV["BLAZER_DATABASE_URL"] %>
#
#    # statement timeout, in seconds
#    # none by default
#    # timeout: 15
#
#    # caching settings
#    # can greatly improve speed
#    # off by default
#    # cache:
#    #   mode: slow # or all
#    #   expires_in: 60 # min
#    #   slow_threshold: 15 # sec, only used in slow mode
#
#    # wrap queries in a transaction for safety
#    # not necessary if you use a read-only user
#    # true by default
#    # use_transaction: false
#
#    smart_variables:
#      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
#      # period: ["day", "week", "month"]
#      # status: {0: "Active", 1: "Archived"}
#
#    linked_columns:
#      # user_id: "/admin/users/{value}"
#
#    smart_columns:
#      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

  Big Query:
    adapter: bigquery
    project: cashslide-847f7
    keyfile: './gcp-keyfile.json'

    awesome_variables:
      target_data:
        value: [
                { "name" : "device_id", "condition" : "device_id" },
                { "name" : "google_ad_id", "condition" : "google_ad_id" },
                { "name" : "전체 개수", "condition" : "count(*)" }
              ]
        style: select
        type: condition
      tags:
        value: [
          {"name" : "FashionF", "condition" : "FashionF >= 1"},
          {"name" : "FashionM", "condition" : "FashionM >= 1"},
          {"name" : "Restaurant", "condition" : "Restaurant >= 1"},
          {"name" : "Puzzle", "condition" : "Puzzle >= 1"},
          {"name" : "Finance", "condition" : "Finance >= 1"},
          {"name" : "Beauty", "condition" : "Beauty >= 1"},
          {"name" : "Baby", "condition" : "Baby >= 1"},
          {"name" : "Simulation", "condition" : "Simulation >= 1"},
          {"name" : "Real", "condition" : "Real >= 1"},
          {"name" : "Luxury", "condition" : "Luxury >= 1"},
          {"name" : "Kids", "condition" : "Kids >= 1"},
          {"name" : "Board", "condition" : "Board >= 1"},
          {"name" : "Medical", "condition" : "Medical >= 1"},
          {"name" : "Cosmetic", "condition" : "Cosmetic >= 1"},
          {"name" : "Language", "condition" : "Language >= 1"},
          {"name" : "RPG", "condition" : "RPG >= 1"},
          {"name" : "Fitness", "condition" : "Fitness >= 1"},
          {"name" : "Shopping", "condition" : "Shopping >= 1"},
          {"name" : "Middle", "condition" : "Middle >= 1"},
          {"name" : "Action", "condition" : "Action >= 1"},
          {"name" : "SportsG", "condition" : "SportsG >= 1"},
          {"name" : "Membership", "condition" : "Membership >= 1"},
          {"name" : "License", "condition" : "License >= 1"},
          {"name" : "SportsA", "condition" : "SportsA >= 1"},
          {"name" : "Sports", "condition" : "Sports >= 1"},
          {"name" : "Golf", "condition" : "Golf >= 1"},
          {"name" : "Grocery", "condition" : "Grocery >= 1"},
          {"name" : "Media", "condition" : "Media >= 1"},
          {"name" : "Strategy", "condition" : "Strategy >= 1"},
          {"name" : "Leisure", "condition" : "Leisure >= 1"},
          {"name" : "Electronics", "condition" : "Electronics >= 1"},
          {"name" : "Movies", "condition" : "Movies >= 1"},
          {"name" : "Smartphone", "condition" : "Smartphone >= 1"},
          {"name" : "Auto", "condition" : "Auto >= 1"},
          {"name" : "Pet", "condition" : "Pet >= 1"},
          {"name" : "Music", "condition" : "Music >= 1"},
          {"name" : "High", "condition" : "High >= 1"},
          {"name" : "Date", "condition" : "Date >= 1"},
          {"name" : "Living", "condition" : "Living >= 1"},
          {"name" : "Webcomic", "condition" : "Webcomic >= 1"},
          {"name" : "Wedding", "condition" : "Wedding >= 1"},
          {"name" : "Cooking", "condition" : "Cooking >= 1"},
          {"name" : "Books", "condition" : "Books >= 1"},
          {"name" : "Hotels", "condition" : "Hotels >= 1"},
          {"name" : "Current", "condition" : "Current >= 1"},
          {"name" : "Coffee", "condition" : "Coffee >= 1"},
          {"name" : "Tickets", "condition" : "Tickets >= 1"},
          {"name" : "Car", "condition" : "Car >= 1"},
          {"name" : "Donation", "condition" : "Donation >= 1"},
          {"name" : "Liquor", "condition" : "Liquor >= 1"},
          {"name" : "Others", "condition" : "Others >= 1"},
          {"name" : "Travel", "condition" : "Travel >= 1"},
          {"name" : "Event", "condition" : "Event >= 1"},
          {"name" : "Delivery", "condition" : "Delivery >= 1"},
          {"name" : "PC", "condition" : "PC >= 1"},
          {"name" : "Credit", "condition" : "Credit >= 1"},
          {"name" : "Snack", "condition" : "Snack >= 1"},
          {"name" : "Game", "condition" : "Game >= 1"},
          
          ]
        style: checkbox  # (value에서 선택 select | radio | checkbox | (여기서부터는 직접 입력) datepicker | textfield
        type: condition  # string | condition | date | datetime
      gender:
        value: [
            { "name" : "전체", "condition" : "true" },
            { "name" : "남자", "condition" : "sex = 1" },
            { "name" : "여자", "condition" : "sex = 2" }
          ]
        style: select  # (value에서 선택 select | radio | checkbox | (여기서부터는 직접 입력) datepicker | text
        type: condition  # string | condition | date | datetime
      marriage:
        value: [
            { "name" : "전체", "condition" : "true" },
            { "name" : "미혼", "condition" : "marriage = 0" },
            { "name" : "기혼", "condition" : "marriage = 1" }
          ]
        style: select  # (value에서 선택 select | radio | checkbox | (여기서부터는 직접 입력) datepicker | text
        type: condition  # string | condition | date | datetime
      age:
        value: [
            { "name" : "10대", "condition" : "(EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age >= 10 AND EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age < 20)" },
            { "name" : "20대", "condition" : "(EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age >= 20 AND EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age < 30)" },
            { "name" : "30대", "condition" : "(EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age >= 30 AND EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age < 40)" },
            { "name" : "40대", "condition" : "(EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age >= 40 AND EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age < 50)" },
            { "name" : "50대", "condition" : "(EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age >= 50 AND EXTRACT(ISOYEAR FROM CURRENT_DATE()) - age < 60)" },
            { "name" : "60대 이상", "condition" : "(year - age >= 60 AND)" },
          ]
        style: checkbox  # (value에서 선택 select | radio | checkbox | (여기서부터는 직접 입력) datepicker | textfield
        type: condition  # string | condition | date | datetime
  Athena:
    adapter: athena
    database: database
    output_location: s3://some-bucket/

#  MySQL:
#    url: mysql2://user:password@hostname:3306/database
#
#  Elasticsearch:
#    adapter: elasticsearch
#    url: http://user:password@hostname:9200

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
# user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# optional auth method to use as a before_action (default: nil)
# before_action: :authenticate!

# email to send checks from
# from_email: blazer@example.org

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

