# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

sandbox:
  adapter: mysql2
  database: sandbox_wheelhouse
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  username: nbtmaster
  password: wldrltm1227
  pool: 20
  port: 3306
  timeout: 5000
  host: 172.27.0.65

production:
  adapter: mysql2
  database: wheelhouse
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  username: root
  password: k220jk220j@
  pool: 20
  port: 3306
  timeout: 5000
  host: localhost
